// Indian States and Cities Data
export interface City {
  name: string
  code: string
}

export interface State {
  name: string
  code: string
  cities: City[]
}

export const INDIAN_STATES: State[] = [
  {
    name: "Andhra Pradesh",
    code: "AP",
    cities: [
      { name: "Anantapur", code: "ATP" },
      { name: "Chittoor", code: "CTO" },
      { name: "East Godavari", code: "EGD" },
      { name: "Guntur", code: "GNT" },
      { name: "Krishna", code: "KRS" },
      { name: "Kurnool", code: "KRN" },
      { name: "Nellore", code: "NLR" },
      { name: "Prakasam", code: "PKS" },
      { name: "Srikakulam", code: "SKL" },
      { name: "Visakhapatnam", code: "VTZ" },
      { name: "Vizianagaram", code: "VZN" },
      { name: "West Godavari", code: "WGD" },
      { name: "YSR Kadapa", code: "YSR" }
    ]
  },
  {
    name: "Arunachal Pradesh",
    code: "AR",
    cities: [
      { name: "Anjaw", code: "ANJ" },
      { name: "Changlang", code: "CGL" },
      { name: "Dibang Valley", code: "DBV" },
      { name: "East Kameng", code: "EKM" },
      { name: "East Siang", code: "ESG" },
      { name: "Kamle", code: "KML" },
      { name: "Kra Daadi", code: "KDD" },
      { name: "Kurung Kumey", code: "KKY" },
      { name: "Lepa Rada", code: "LRD" },
      { name: "Lohit", code: "LHT" },
      { name: "Longding", code: "LDG" },
      { name: "Lower Dibang Valley", code: "LDV" },
      { name: "Lower Siang", code: "LSG" },
      { name: "Lower Subansiri", code: "LSB" },
      { name: "Namsai", code: "NMS" },
      { name: "Pakke Kessang", code: "PKK" },
      { name: "Papum Pare", code: "PPR" },
      { name: "Shi Yomi", code: "SYM" },
      { name: "Siang", code: "SNG" },
      { name: "Tawang", code: "TWG" },
      { name: "Tirap", code: "TRP" },
      { name: "Upper Siang", code: "USG" },
      { name: "Upper Subansiri", code: "USB" },
      { name: "West Kameng", code: "WKM" },
      { name: "West Siang", code: "WSG" }
    ]
  },
  {
    name: "Assam",
    code: "AS",
    cities: [
      { name: "Baksa", code: "BKS" },
      { name: "Barpeta", code: "BRP" },
      { name: "Biswanath", code: "BSW" },
      { name: "Bongaigaon", code: "BNG" },
      { name: "Cachar", code: "CCR" },
      { name: "Charaideo", code: "CRD" },
      { name: "Chirang", code: "CHR" },
      { name: "Darrang", code: "DRG" },
      { name: "Dhemaji", code: "DHM" },
      { name: "Dhubri", code: "DHB" },
      { name: "Dibrugarh", code: "DBG" },
      { name: "Dima Hasao", code: "DHS" },
      { name: "Goalpara", code: "GLP" },
      { name: "Golaghat", code: "GLG" },
      { name: "Hailakandi", code: "HLK" },
      { name: "Hojai", code: "HJI" },
      { name: "Jorhat", code: "JRH" },
      { name: "Kamrup", code: "KMP" },
      { name: "Kamrup Metropolitan", code: "KMM" },
      { name: "Karbi Anglong", code: "KAL" },
      { name: "Karimganj", code: "KMG" },
      { name: "Kokrajhar", code: "KKR" },
      { name: "Lakhimpur", code: "LKP" },
      { name: "Majuli", code: "MJL" },
      { name: "Morigaon", code: "MRG" },
      { name: "Nagaon", code: "NGN" },
      { name: "Nalbari", code: "NLB" },
      { name: "Sivasagar", code: "SVS" },
      { name: "Sonitpur", code: "SNT" },
      { name: "South Salmara-Mankachar", code: "SSM" },
      { name: "Tinsukia", code: "TNS" },
      { name: "Udalguri", code: "UDL" },
      { name: "West Karbi Anglong", code: "WKA" }
    ]
  },
  {
    name: "Bihar",
    code: "BR",
    cities: [
      { name: "Araria", code: "ARA" },
      { name: "Arwal", code: "ARW" },
      { name: "Aurangabad", code: "AUR" },
      { name: "Banka", code: "BNK" },
      { name: "Begusarai", code: "BGS" },
      { name: "Bhagalpur", code: "BGP" },
      { name: "Bhojpur", code: "BHJ" },
      { name: "Buxar", code: "BXR" },
      { name: "Darbhanga", code: "DBG" },
      { name: "East Champaran", code: "ECH" },
      { name: "Gaya", code: "GAY" },
      { name: "Gopalganj", code: "GPL" },
      { name: "Jamui", code: "JMU" },
      { name: "Jehanabad", code: "JHB" },
      { name: "Kaimur", code: "KMR" },
      { name: "Katihar", code: "KTH" },
      { name: "Khagaria", code: "KHG" },
      { name: "Kishanganj", code: "KSG" },
      { name: "Lakhisarai", code: "LKS" },
      { name: "Madhepura", code: "MDP" },
      { name: "Madhubani", code: "MDB" },
      { name: "Munger", code: "MNG" },
      { name: "Muzaffarpur", code: "MZU" },
      { name: "Nalanda", code: "NLD" },
      { name: "Nawada", code: "NWD" },
      { name: "Patna", code: "PAT" },
      { name: "Purnia", code: "PRN" },
      { name: "Rohtas", code: "RHT" },
      { name: "Saharsa", code: "SHR" },
      { name: "Samastipur", code: "SMP" },
      { name: "Saran", code: "SRN" },
      { name: "Sheikhpura", code: "SHP" },
      { name: "Sheohar", code: "SHH" },
      { name: "Sitamarhi", code: "STM" },
      { name: "Siwan", code: "SWN" },
      { name: "Supaul", code: "SPL" },
      { name: "Vaishali", code: "VSH" },
      { name: "West Champaran", code: "WCH" }
    ]
  },
  {
    name: "Chhattisgarh",
    code: "CG",
    cities: [
      { name: "Balod", code: "BLD" },
      { name: "Baloda Bazar", code: "BLB" },
      { name: "Balrampur", code: "BLR" },
      { name: "Bastar", code: "BST" },
      { name: "Bemetara", code: "BMT" },
      { name: "Bijapur", code: "BJP" },
      { name: "Bilaspur", code: "BLP" },
      { name: "Dantewada", code: "DNT" },
      { name: "Dhamtari", code: "DHM" },
      { name: "Durg", code: "DRG" },
      { name: "Gariaband", code: "GRB" },
      { name: "Gaurela Pendra Marwahi", code: "GPM" },
      { name: "Janjgir Champa", code: "JJC" },
      { name: "Jashpur", code: "JSP" },
      { name: "Kabirdham", code: "KBD" },
      { name: "Kanker", code: "KNK" },
      { name: "Kondagaon", code: "KDG" },
      { name: "Korba", code: "KRB" },
      { name: "Koriya", code: "KRY" },
      { name: "Mahasamund", code: "MHS" },
      { name: "Mungeli", code: "MNG" },
      { name: "Narayanpur", code: "NRP" },
      { name: "Raigarh", code: "RGH" },
      { name: "Raipur", code: "RPR" },
      { name: "Rajnandgaon", code: "RJN" },
      { name: "Sukma", code: "SKM" },
      { name: "Surajpur", code: "SRP" },
      { name: "Surguja", code: "SRG" }
    ]
  },
  {
    name: "Goa",
    code: "GA",
    cities: [
      { name: "Panaji", code: "PNJ" },
      { name: "Margao", code: "MGO" },
      { name: "Vasco da Gama", code: "VSC" },
      { name: "Mapusa", code: "MPS" }
    ]
  },
  {
    name: "Gujarat",
    code: "GJ",
    cities: [
      { name: "Ahmedabad", code: "AMD" },
      { name: "Amreli", code: "AMR" },
      { name: "Anand", code: "AND" },
      { name: "Aravalli", code: "ARV" },
      { name: "Banaskantha", code: "BNS" },
      { name: "Bharuch", code: "BHR" },
      { name: "Bhavnagar", code: "BHV" },
      { name: "Botad", code: "BTD" },
      { name: "Chhota Udepur", code: "CHU" },
      { name: "Dahod", code: "DHD" },
      { name: "Dang", code: "DNG" },
      { name: "Devbhoomi Dwarka", code: "DDW" },
      { name: "Gandhinagar", code: "GDN" },
      { name: "Gir Somnath", code: "GSM" },
      { name: "Jamnagar", code: "JMN" },
      { name: "Junagadh", code: "JNG" },
      { name: "Kheda", code: "KHD" },
      { name: "Kutch", code: "KTC" },
      { name: "Mahisagar", code: "MHS" },
      { name: "Mehsana", code: "MHS" },
      { name: "Morbi", code: "MRB" },
      { name: "Narmada", code: "NRM" },
      { name: "Navsari", code: "NVS" },
      { name: "Panchmahal", code: "PCM" },
      { name: "Patan", code: "PTN" },
      { name: "Porbandar", code: "PBD" },
      { name: "Rajkot", code: "RJK" },
      { name: "Sabarkantha", code: "SBK" },
      { name: "Surat", code: "SRT" },
      { name: "Surendranagar", code: "SRN" },
      { name: "Tapi", code: "TPI" },
      { name: "Vadodara", code: "VDR" },
      { name: "Valsad", code: "VLS" }
    ]
  },
  {
    name: "Haryana",
    code: "HR",
    cities: [
      { name: "Ambala", code: "AMB" },
      { name: "Bhiwani", code: "BHW" },
      { name: "Charkhi Dadri", code: "CDD" },
      { name: "Faridabad", code: "FBD" },
      { name: "Fatehabad", code: "FTB" },
      { name: "Gurugram", code: "GGN" },
      { name: "Hisar", code: "HSR" },
      { name: "Jhajjar", code: "JHJ" },
      { name: "Jind", code: "JND" },
      { name: "Kaithal", code: "KTH" },
      { name: "Karnal", code: "KRN" },
      { name: "Kurukshetra", code: "KRK" },
      { name: "Mahendragarh", code: "MHG" },
      { name: "Nuh", code: "NUH" },
      { name: "Palwal", code: "PLW" },
      { name: "Panchkula", code: "PKL" },
      { name: "Panipat", code: "PNP" },
      { name: "Rewari", code: "RWR" },
      { name: "Rohtak", code: "RTK" },
      { name: "Sirsa", code: "SRS" },
      { name: "Sonipat", code: "SNP" },
      { name: "Yamunanagar", code: "YMN" }
    ]
  },
  {
    name: "Himachal Pradesh",
    code: "HP",
    cities: [
      { name: "Bilaspur", code: "BLP" },
      { name: "Chamba", code: "CHM" },
      { name: "Hamirpur", code: "HMP" },
      { name: "Kangra", code: "KNG" },
      { name: "Kinnaur", code: "KNR" },
      { name: "Kullu", code: "KLL" },
      { name: "Lahaul and Spiti", code: "LHS" },
      { name: "Mandi", code: "MND" },
      { name: "Shimla", code: "SML" },
      { name: "Sirmaur", code: "SRM" },
      { name: "Solan", code: "SOL" },
      { name: "Una", code: "UNA" }
    ]
  },
  {
    name: "Jharkhand",
    code: "JH",
    cities: [
      { name: "Bokaro", code: "BKR" },
      { name: "Chatra", code: "CTR" },
      { name: "Deoghar", code: "DGH" },
      { name: "Dhanbad", code: "DNB" },
      { name: "Dumka", code: "DMK" },
      { name: "East Singhbhum", code: "ESB" },
      { name: "Garhwa", code: "GRW" },
      { name: "Giridih", code: "GRD" },
      { name: "Godda", code: "GDD" },
      { name: "Gumla", code: "GML" },
      { name: "Hazaribagh", code: "HZB" },
      { name: "Jamtara", code: "JMT" },
      { name: "Khunti", code: "KHT" },
      { name: "Koderma", code: "KDM" },
      { name: "Latehar", code: "LTH" },
      { name: "Lohardaga", code: "LHD" },
      { name: "Pakur", code: "PKR" },
      { name: "Palamu", code: "PLM" },
      { name: "Ramgarh", code: "RMG" },
      { name: "Ranchi", code: "RNC" },
      { name: "Sahibganj", code: "SHG" },
      { name: "Seraikela Kharsawan", code: "SKK" },
      { name: "Simdega", code: "SMD" },
      { name: "West Singhbhum", code: "WSB" }
    ]
  },
  {
    name: "Karnataka",
    code: "KA",
    cities: [
      { name: "Bagalkot", code: "BGL" },
      { name: "Ballari", code: "BLR" },
      { name: "Belagavi", code: "BLG" },
      { name: "Bengaluru Rural", code: "BGR" },
      { name: "Bengaluru Urban", code: "BLR" },
      { name: "Bidar", code: "BDR" },
      { name: "Chamarajanagar", code: "CRJ" },
      { name: "Chikballapur", code: "CKB" },
      { name: "Chikkamagaluru", code: "CKM" },
      { name: "Chitradurga", code: "CTD" },
      { name: "Dakshina Kannada", code: "DKN" },
      { name: "Davanagere", code: "DVG" },
      { name: "Dharwad", code: "DHW" },
      { name: "Gadag", code: "GDG" },
      { name: "Hassan", code: "HSN" },
      { name: "Haveri", code: "HVR" },
      { name: "Kalaburagi", code: "KLB" },
      { name: "Kodagu", code: "KDG" },
      { name: "Kolar", code: "KLR" },
      { name: "Koppal", code: "KPL" },
      { name: "Mandya", code: "MND" },
      { name: "Mysuru", code: "MYS" },
      { name: "Raichur", code: "RCR" },
      { name: "Ramanagara", code: "RMN" },
      { name: "Shivamogga", code: "SHM" },
      { name: "Tumakuru", code: "TMK" },
      { name: "Udupi", code: "UDP" },
      { name: "Uttara Kannada", code: "UKN" },
      { name: "Vijayapura", code: "VJP" },
      { name: "Yadgir", code: "YDG" }
    ]
  },
  {
    name: "Kerala",
    code: "KL",
    cities: [
      { name: "Alappuzha", code: "ALP" },
      { name: "Ernakulam", code: "ERN" },
      { name: "Idukki", code: "IDK" },
      { name: "Kannur", code: "CNN" },
      { name: "Kasaragod", code: "KSG" },
      { name: "Kollam", code: "QLN" },
      { name: "Kottayam", code: "KTM" },
      { name: "Kozhikode", code: "CCJ" },
      { name: "Malappuram", code: "MLP" },
      { name: "Palakkad", code: "PKD" },
      { name: "Pathanamthitta", code: "PTN" },
      { name: "Thiruvananthapuram", code: "TRV" },
      { name: "Thrissur", code: "TCR" },
      { name: "Wayanad", code: "WYN" }
    ]
  },
  {
    name: "Madhya Pradesh",
    code: "MP",
    cities: [
      { name: "ABHANA", code: "ABH" },
      { name: "AGAR MALWA", code: "AGM" },
      { name: "AHMEDPUR", code: "AHP" },
      { name: "AJAYGARH", code: "AJG" },
      { name: "AKODIYAMANDI", code: "AKD" },
      { name: "ALAMPUR", code: "ALP" },
      { name: "ALIRAJPUR", code: "ALR" },
      { name: "ALOT", code: "ALT" },
      { name: "AMANGANJ", code: "AMG" },
      { name: "AMARPATAN", code: "AMP" },
      { name: "AMARWADA (CHD)", code: "AWD" },
      { name: "AMBAH", code: "AMB" },
      { name: "AMGAON BADA", code: "AGB" },
      { name: "AMHERA", code: "AMH" },
      { name: "AMLA", code: "AML" },
      { name: "AMLAHA", code: "AMA" },
      { name: "Bhopal", code: "BHO" },
      { name: "Indore", code: "IDR" },
      { name: "Gwalior", code: "GWL" },
      { name: "Jabalpur", code: "JBP" },
      { name: "Ujjain", code: "UJN" },
      { name: "Sagar", code: "SGR" },
      { name: "Dewas", code: "DWS" },
      { name: "Satna", code: "STN" },
      { name: "Ratlam", code: "RTM" },
      { name: "Rewa", code: "RWA" },
      { name: "Betul", code: "BTL" },
      { name: "Burhanpur", code: "BHP" },
      { name: "Chhindwara", code: "CHD" },
      { name: "Damoh", code: "DMH" },
      { name: "Datia", code: "DTA" },
      { name: "Dhar", code: "DHR" },
      { name: "Guna", code: "GNA" },
      { name: "Harda", code: "HRD" },
      { name: "Hoshangabad", code: "HSB" },
      { name: "Jhabua", code: "JHB" },
      { name: "Katni", code: "KTN" },
      { name: "Khandwa", code: "KHD" },
      { name: "Khargone", code: "KHG" },
      { name: "Mandla", code: "MDL" },
      { name: "Mandsaur", code: "MDS" },
      { name: "Morena", code: "MRN" },
      { name: "Narsinghpur", code: "NSP" },
      { name: "Neemuch", code: "NMC" },
      { name: "Panna", code: "PNN" },
      { name: "Raisen", code: "RSN" },
      { name: "Rajgarh", code: "RJG" },
      { name: "Ratlam", code: "RTL" },
      { name: "Sehore", code: "SHR" },
      { name: "Seoni", code: "SNI" },
      { name: "Shahdol", code: "SHD" },
      { name: "Shajapur", code: "SJP" },
      { name: "Sheopur", code: "SHP" },
      { name: "Shivpuri", code: "SVP" },
      { name: "Sidhi", code: "SDH" },
      { name: "Singrauli", code: "SGL" },
      { name: "Tikamgarh", code: "TKG" },
      { name: "Umaria", code: "UMR" },
      { name: "Vidisha", code: "VDS" }
    ]
  },
  {
    name: "Maharashtra",
    code: "MH",
    cities: [
      { name: "Ahmednagar", code: "AHM" },
      { name: "Akola", code: "AKL" },
      { name: "Amravati", code: "AMI" },
      { name: "Aurangabad", code: "IXU" },
      { name: "Beed", code: "BED" },
      { name: "Bhandara", code: "BHD" },
      { name: "Buldhana", code: "BLD" },
      { name: "Chandrapur", code: "CDP" },
      { name: "Dhule", code: "DHL" },
      { name: "Gadchiroli", code: "GDC" },
      { name: "Gondia", code: "GND" },
      { name: "Hingoli", code: "HNG" },
      { name: "Jalgaon", code: "JLG" },
      { name: "Jalna", code: "JLN" },
      { name: "Kolhapur", code: "KOP" },
      { name: "Latur", code: "LTR" },
      { name: "Mumbai City", code: "BOM" },
      { name: "Mumbai Suburban", code: "MBS" },
      { name: "Nagpur", code: "NAG" },
      { name: "Nanded", code: "NND" },
      { name: "Nandurbar", code: "NDB" },
      { name: "Nashik", code: "NSK" },
      { name: "Osmanabad", code: "OSM" },
      { name: "Palghar", code: "PLG" },
      { name: "Parbhani", code: "PRB" },
      { name: "Pune", code: "PNQ" },
      { name: "Raigad", code: "RGD" },
      { name: "Ratnagiri", code: "RTN" },
      { name: "Sangli", code: "SGL" },
      { name: "Satara", code: "STR" },
      { name: "Sindhudurg", code: "SND" },
      { name: "Solapur", code: "SSE" },
      { name: "Thane", code: "TNE" },
      { name: "Wardha", code: "WRD" },
      { name: "Washim", code: "WSH" },
      { name: "Yavatmal", code: "YVT" }
    ]
  },
  {
    name: "Manipur",
    code: "MN",
    cities: [
      { name: "Bishnupur", code: "BSN" },
      { name: "Chandel", code: "CDL" },
      { name: "Churachandpur", code: "CCH" },
      { name: "Imphal East", code: "IME" },
      { name: "Imphal West", code: "IMW" },
      { name: "Jiribam", code: "JRB" },
      { name: "Kakching", code: "KKC" },
      { name: "Kamjong", code: "KMJ" },
      { name: "Kangpokpi", code: "KPK" },
      { name: "Noney", code: "NON" },
      { name: "Pherzawl", code: "PHZ" },
      { name: "Senapati", code: "SNP" },
      { name: "Tamenglong", code: "TML" },
      { name: "Tengnoupal", code: "TGN" },
      { name: "Thoubal", code: "THB" },
      { name: "Ukhrul", code: "UKH" }
    ]
  },
  {
    name: "Meghalaya",
    code: "ML",
    cities: [
      { name: "East Garo Hills", code: "EGH" },
      { name: "East Jaintia Hills", code: "EJH" },
      { name: "East Khasi Hills", code: "EKH" },
      { name: "North Garo Hills", code: "NGH" },
      { name: "Ri Bhoi", code: "RBH" },
      { name: "South Garo Hills", code: "SGH" },
      { name: "South West Garo Hills", code: "SWG" },
      { name: "South West Khasi Hills", code: "SWK" },
      { name: "West Garo Hills", code: "WGH" },
      { name: "West Jaintia Hills", code: "WJH" },
      { name: "West Khasi Hills", code: "WKH" }
    ]
  },
  {
    name: "Mizoram",
    code: "MZ",
    cities: [
      { name: "Aizawl", code: "AJL" },
      { name: "Champhai", code: "CMP" },
      { name: "Hnahthial", code: "HNH" },
      { name: "Kolasib", code: "KLS" },
      { name: "Khawzawl", code: "KHZ" },
      { name: "Lawngtlai", code: "LWT" },
      { name: "Lunglei", code: "LGL" },
      { name: "Mamit", code: "MMT" },
      { name: "Saiha", code: "SIH" },
      { name: "Saitual", code: "STL" },
      { name: "Serchhip", code: "SRC" }
    ]
  },
  {
    name: "Nagaland",
    code: "NL",
    cities: [
      { name: "Dimapur", code: "DMR" },
      { name: "Kiphire", code: "KPH" },
      { name: "Kohima", code: "KHM" },
      { name: "Longleng", code: "LLG" },
      { name: "Mokokchung", code: "MKC" },
      { name: "Mon", code: "MON" },
      { name: "Noklak", code: "NKL" },
      { name: "Peren", code: "PRN" },
      { name: "Phek", code: "PHK" },
      { name: "Tuensang", code: "TSG" },
      { name: "Wokha", code: "WKH" },
      { name: "Zunheboto", code: "ZNH" }
    ]
  },
  {
    name: "Odisha",
    code: "OR",
    cities: [
      { name: "Angul", code: "ANG" },
      { name: "Balangir", code: "BLG" },
      { name: "Balasore", code: "BLS" },
      { name: "Bargarh", code: "BRG" },
      { name: "Bhadrak", code: "BHD" },
      { name: "Boudh", code: "BDH" },
      { name: "Cuttack", code: "CTC" },
      { name: "Deogarh", code: "DGH" },
      { name: "Dhenkanal", code: "DHK" },
      { name: "Gajapati", code: "GJP" },
      { name: "Ganjam", code: "GNJ" },
      { name: "Jagatsinghpur", code: "JSP" },
      { name: "Jajpur", code: "JJP" },
      { name: "Jharsuguda", code: "JHS" },
      { name: "Kalahandi", code: "KLH" },
      { name: "Kandhamal", code: "KDM" },
      { name: "Kendrapara", code: "KDP" },
      { name: "Kendujhar", code: "KDJ" },
      { name: "Khordha", code: "KHR" },
      { name: "Koraput", code: "KRP" },
      { name: "Malkangiri", code: "MLK" },
      { name: "Mayurbhanj", code: "MYB" },
      { name: "Nabarangpur", code: "NBR" },
      { name: "Nayagarh", code: "NYG" },
      { name: "Nuapada", code: "NUP" },
      { name: "Puri", code: "PRI" },
      { name: "Rayagada", code: "RYG" },
      { name: "Sambalpur", code: "SBP" },
      { name: "Subarnapur", code: "SBN" },
      { name: "Sundargarh", code: "SND" }
    ]
  },
  {
    name: "Punjab",
    code: "PB",
    cities: [
      { name: "Amritsar", code: "ATQ" },
      { name: "Barnala", code: "BRN" },
      { name: "Bathinda", code: "BTI" },
      { name: "Faridkot", code: "FDK" },
      { name: "Fatehgarh Sahib", code: "FGS" },
      { name: "Fazilka", code: "FZK" },
      { name: "Ferozepur", code: "FZR" },
      { name: "Gurdaspur", code: "GDP" },
      { name: "Hoshiarpur", code: "HSP" },
      { name: "Jalandhar", code: "JLR" },
      { name: "Kapurthala", code: "KPT" },
      { name: "Ludhiana", code: "LUH" },
      { name: "Malerkotla", code: "MLK" },
      { name: "Mansa", code: "MNS" },
      { name: "Moga", code: "MOG" },
      { name: "Muktsar", code: "MKT" },
      { name: "Nawanshahr", code: "NWS" },
      { name: "Pathankot", code: "PTK" },
      { name: "Patiala", code: "PTA" },
      { name: "Rupnagar", code: "RPN" },
      { name: "Sahibzada Ajit Singh Nagar", code: "SAS" },
      { name: "Sangrur", code: "SGR" },
      { name: "Tarn Taran", code: "TTR" }
    ]
  },
  {
    name: "Rajasthan",
    code: "RJ",
    cities: [
      { name: "Ajmer", code: "AJM" },
      { name: "Alwar", code: "AWR" },
      { name: "Banswara", code: "BSW" },
      { name: "Baran", code: "BRN" },
      { name: "Barmer", code: "BMR" },
      { name: "Bharatpur", code: "BTP" },
      { name: "Bhilwara", code: "BHL" },
      { name: "Bikaner", code: "BKN" },
      { name: "Bundi", code: "BND" },
      { name: "Chittorgarh", code: "CTG" },
      { name: "Churu", code: "CHR" },
      { name: "Dausa", code: "DSA" },
      { name: "Dholpur", code: "DHP" },
      { name: "Dungarpur", code: "DGP" },
      { name: "Hanumangarh", code: "HMG" },
      { name: "Jaipur", code: "JAI" },
      { name: "Jaisalmer", code: "JSL" },
      { name: "Jalore", code: "JLR" },
      { name: "Jhalawar", code: "JHW" },
      { name: "Jhunjhunu", code: "JHJ" },
      { name: "Jodhpur", code: "JDH" },
      { name: "Karauli", code: "KRL" },
      { name: "Kota", code: "KTU" },
      { name: "Nagaur", code: "NGR" },
      { name: "Pali", code: "PLI" },
      { name: "Pratapgarh", code: "PTG" },
      { name: "Rajsamand", code: "RJS" },
      { name: "Sawai Madhopur", code: "SMP" },
      { name: "Sikar", code: "SKR" },
      { name: "Sirohi", code: "SRH" },
      { name: "Sri Ganganagar", code: "SGG" },
      { name: "Tonk", code: "TNK" },
      { name: "Udaipur", code: "UDR" }
    ]
  },
  {
    name: "Sikkim",
    code: "SK",
    cities: [
      { name: "East Sikkim", code: "ESK" },
      { name: "North Sikkim", code: "NSK" },
      { name: "South Sikkim", code: "SSK" },
      { name: "West Sikkim", code: "WSK" }
    ]
  },
  {
    name: "Tamil Nadu",
    code: "TN",
    cities: [
      { name: "Ariyalur", code: "ARY" },
      { name: "Chengalpattu", code: "CGP" },
      { name: "Chennai", code: "MAA" },
      { name: "Coimbatore", code: "CJB" },
      { name: "Cuddalore", code: "CDL" },
      { name: "Dharmapuri", code: "DHP" },
      { name: "Dindigul", code: "DGL" },
      { name: "Erode", code: "ERD" },
      { name: "Kallakurichi", code: "KLK" },
      { name: "Kanchipuram", code: "KCP" },
      { name: "Kanyakumari", code: "KNY" },
      { name: "Karur", code: "KRR" },
      { name: "Krishnagiri", code: "KRG" },
      { name: "Madurai", code: "IXM" },
      { name: "Mayiladuthurai", code: "MYL" },
      { name: "Nagapattinam", code: "NGP" },
      { name: "Namakkal", code: "NMK" },
      { name: "Nilgiris", code: "NLG" },
      { name: "Perambalur", code: "PRM" },
      { name: "Pudukkottai", code: "PDK" },
      { name: "Ramanathapuram", code: "RMN" },
      { name: "Ranipet", code: "RNP" },
      { name: "Salem", code: "SXV" },
      { name: "Sivaganga", code: "SVG" },
      { name: "Tenkasi", code: "TNK" },
      { name: "Thanjavur", code: "THJ" },
      { name: "Theni", code: "THN" },
      { name: "Thoothukudi", code: "TCR" },
      { name: "Tiruchirappalli", code: "TRZ" },
      { name: "Tirunelveli", code: "TEZ" },
      { name: "Tirupathur", code: "TPT" },
      { name: "Tiruppur", code: "TRP" },
      { name: "Tiruvallur", code: "TVL" },
      { name: "Tiruvannamalai", code: "TVM" },
      { name: "Tiruvarur", code: "TVR" },
      { name: "Vellore", code: "VLR" },
      { name: "Viluppuram", code: "VLP" },
      { name: "Virudhunagar", code: "VDN" }
    ]
  },
  {
    name: "Telangana",
    code: "TG",
    cities: [
      { name: "Adilabad", code: "ADB" },
      { name: "Bhadradri Kothagudem", code: "BKG" },
      { name: "Hyderabad", code: "HYD" },
      { name: "Jagtial", code: "JGT" },
      { name: "Jangaon", code: "JNG" },
      { name: "Jayashankar Bhupalpally", code: "JBP" },
      { name: "Jogulamba Gadwal", code: "JGD" },
      { name: "Kamareddy", code: "KMR" },
      { name: "Karimnagar", code: "KMN" },
      { name: "Khammam", code: "KMM" },
      { name: "Komaram Bheem Asifabad", code: "KBA" },
      { name: "Mahabubabad", code: "MBB" },
      { name: "Mahabubnagar", code: "MBN" },
      { name: "Mancherial", code: "MCH" },
      { name: "Medak", code: "MDK" },
      { name: "Medchal Malkajgiri", code: "MMG" },
      { name: "Mulugu", code: "MLG" },
      { name: "Nagarkurnool", code: "NKL" },
      { name: "Nalgonda", code: "NLG" },
      { name: "Narayanpet", code: "NRP" },
      { name: "Nirmal", code: "NRM" },
      { name: "Nizamabad", code: "NZB" },
      { name: "Peddapalli", code: "PDP" },
      { name: "Rajanna Sircilla", code: "RSC" },
      { name: "Rangareddy", code: "RRD" },
      { name: "Sangareddy", code: "SGR" },
      { name: "Siddipet", code: "SDP" },
      { name: "Suryapet", code: "SRP" },
      { name: "Vikarabad", code: "VKB" },
      { name: "Wanaparthy", code: "WNP" },
      { name: "Warangal Rural", code: "WGR" },
      { name: "Warangal Urban", code: "WGU" },
      { name: "Yadadri Bhuvanagiri", code: "YBG" }
    ]
  },
  {
    name: "Tripura",
    code: "TR",
    cities: [
      { name: "Dhalai", code: "DHL" },
      { name: "Gomati", code: "GMT" },
      { name: "Khowai", code: "KHW" },
      { name: "North Tripura", code: "NTR" },
      { name: "Sepahijala", code: "SPH" },
      { name: "South Tripura", code: "STR" },
      { name: "Unakoti", code: "UNK" },
      { name: "West Tripura", code: "WTR" }
    ]
  },
  {
    name: "Uttar Pradesh",
    code: "UP",
    cities: [
      { name: "Agra", code: "AGR" },
      { name: "Aligarh", code: "ALG" },
      { name: "Allahabad", code: "IXD" },
      { name: "Ambedkar Nagar", code: "AMN" },
      { name: "Amethi", code: "AMT" },
      { name: "Amroha", code: "AMR" },
      { name: "Auraiya", code: "AUR" },
      { name: "Azamgarh", code: "AZM" },
      { name: "Baghpat", code: "BGP" },
      { name: "Bahraich", code: "BHR" },
      { name: "Ballia", code: "BLL" },
      { name: "Balrampur", code: "BLR" },
      { name: "Banda", code: "BND" },
      { name: "Barabanki", code: "BBK" },
      { name: "Bareilly", code: "BEK" },
      { name: "Basti", code: "BST" },
      { name: "Bhadohi", code: "BDH" },
      { name: "Bijnor", code: "BJN" },
      { name: "Budaun", code: "BDN" },
      { name: "Bulandshahr", code: "BLS" },
      { name: "Chandauli", code: "CDL" },
      { name: "Chitrakoot", code: "CTK" },
      { name: "Deoria", code: "DOR" },
      { name: "Etah", code: "ETH" },
      { name: "Etawah", code: "ETW" },
      { name: "Faizabad", code: "FZB" },
      { name: "Farrukhabad", code: "FRK" },
      { name: "Fatehpur", code: "FTP" },
      { name: "Firozabad", code: "FZD" },
      { name: "Gautam Buddha Nagar", code: "GBN" },
      { name: "Ghaziabad", code: "GZB" },
      { name: "Ghazipur", code: "GZP" },
      { name: "Gonda", code: "GND" },
      { name: "Gorakhpur", code: "GKP" },
      { name: "Hamirpur", code: "HMP" },
      { name: "Hapur", code: "HPR" },
      { name: "Hardoi", code: "HRD" },
      { name: "Hathras", code: "HTR" },
      { name: "Jalaun", code: "JLN" },
      { name: "Jaunpur", code: "JNP" },
      { name: "Jhansi", code: "JHS" },
      { name: "Kannauj", code: "KNJ" },
      { name: "Kanpur Dehat", code: "KPD" },
      { name: "Kanpur Nagar", code: "KNU" },
      { name: "Kasganj", code: "KSG" },
      { name: "Kaushambi", code: "KSB" },
      { name: "Kheri", code: "KHR" },
      { name: "Kushinagar", code: "KSN" },
      { name: "Lalitpur", code: "LLP" },
      { name: "Lucknow", code: "LKO" },
      { name: "Maharajganj", code: "MRG" },
      { name: "Mahoba", code: "MHB" },
      { name: "Mainpuri", code: "MNP" },
      { name: "Mathura", code: "MTR" },
      { name: "Mau", code: "MAU" },
      { name: "Meerut", code: "MRT" },
      { name: "Mirzapur", code: "MZP" },
      { name: "Moradabad", code: "MBD" },
      { name: "Muzaffarnagar", code: "MZN" },
      { name: "Pilibhit", code: "PLB" },
      { name: "Pratapgarh", code: "PTG" },
      { name: "Raebareli", code: "RBL" },
      { name: "Rampur", code: "RMP" },
      { name: "Saharanpur", code: "SHP" },
      { name: "Sambhal", code: "SMB" },
      { name: "Sant Kabir Nagar", code: "SKN" },
      { name: "Shahjahanpur", code: "SJP" },
      { name: "Shamli", code: "SML" },
      { name: "Shravasti", code: "SRV" },
      { name: "Siddharthnagar", code: "SDN" },
      { name: "Sitapur", code: "STP" },
      { name: "Sonbhadra", code: "SNB" },
      { name: "Sultanpur", code: "SLT" },
      { name: "Unnao", code: "UNN" },
      { name: "Varanasi", code: "VNS" }
    ]
  },
  {
    name: "Uttarakhand",
    code: "UK",
    cities: [
      { name: "Almora", code: "ALM" },
      { name: "Bageshwar", code: "BGS" },
      { name: "Chamoli", code: "CML" },
      { name: "Champawat", code: "CMP" },
      { name: "Dehradun", code: "DED" },
      { name: "Haridwar", code: "HRD" },
      { name: "Nainital", code: "NTL" },
      { name: "Pauri Garhwal", code: "PGW" },
      { name: "Pithoragarh", code: "PTG" },
      { name: "Rudraprayag", code: "RDP" },
      { name: "Tehri Garhwal", code: "TGW" },
      { name: "Udham Singh Nagar", code: "USN" },
      { name: "Uttarkashi", code: "UTK" }
    ]
  },
  {
    name: "West Bengal",
    code: "WB",
    cities: [
      { name: "Alipurduar", code: "ALP" },
      { name: "Bankura", code: "BNK" },
      { name: "Birbhum", code: "BRB" },
      { name: "Cooch Behar", code: "COB" },
      { name: "Dakshin Dinajpur", code: "DDJ" },
      { name: "Darjeeling", code: "DJL" },
      { name: "Hooghly", code: "HGL" },
      { name: "Howrah", code: "HWH" },
      { name: "Jalpaiguri", code: "JPG" },
      { name: "Jhargram", code: "JHG" },
      { name: "Kalimpong", code: "KLP" },
      { name: "Kolkata", code: "CCU" },
      { name: "Malda", code: "MLD" },
      { name: "Murshidabad", code: "MSD" },
      { name: "Nadia", code: "NDI" },
      { name: "North 24 Parganas", code: "N24" },
      { name: "Paschim Bardhaman", code: "PBD" },
      { name: "Paschim Medinipur", code: "PMD" },
      { name: "Purba Bardhaman", code: "PBR" },
      { name: "Purba Medinipur", code: "PME" },
      { name: "Purulia", code: "PRL" },
      { name: "South 24 Parganas", code: "S24" },
      { name: "Uttar Dinajpur", code: "UDJ" }
    ]
  }
]

// Union Territories
export const UNION_TERRITORIES: State[] = [
  {
    name: "Andaman and Nicobar Islands",
    code: "AN",
    cities: [
      { name: "Nicobar", code: "NCB" },
      { name: "North and Middle Andaman", code: "NMA" },
      { name: "South Andaman", code: "SAN" }
    ]
  },
  {
    name: "Chandigarh",
    code: "CH",
    cities: [
      { name: "Chandigarh", code: "IXC" }
    ]
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    code: "DN",
    cities: [
      { name: "Dadra and Nagar Haveli", code: "DNH" },
      { name: "Daman", code: "DMN" },
      { name: "Diu", code: "DIU" }
    ]
  },
  {
    name: "Delhi",
    code: "DL",
    cities: [
      { name: "Central Delhi", code: "CDL" },
      { name: "East Delhi", code: "EDL" },
      { name: "New Delhi", code: "NDL" },
      { name: "North Delhi", code: "NDE" },
      { name: "North East Delhi", code: "NED" },
      { name: "North West Delhi", code: "NWD" },
      { name: "Shahdara", code: "SHD" },
      { name: "South Delhi", code: "SDL" },
      { name: "South East Delhi", code: "SED" },
      { name: "South West Delhi", code: "SWD" },
      { name: "West Delhi", code: "WDL" }
    ]
  },
  {
    name: "Jammu and Kashmir",
    code: "JK",
    cities: [
      { name: "Anantnag", code: "ANT" },
      { name: "Bandipora", code: "BDP" },
      { name: "Baramulla", code: "BML" },
      { name: "Budgam", code: "BDG" },
      { name: "Doda", code: "DOD" },
      { name: "Ganderbal", code: "GDB" },
      { name: "Jammu", code: "JMU" },
      { name: "Kathua", code: "KTH" },
      { name: "Kishtwar", code: "KSW" },
      { name: "Kulgam", code: "KLG" },
      { name: "Kupwara", code: "KPW" },
      { name: "Poonch", code: "POO" },
      { name: "Pulwama", code: "PLW" },
      { name: "Rajouri", code: "RJR" },
      { name: "Ramban", code: "RMB" },
      { name: "Reasi", code: "RES" },
      { name: "Samba", code: "SMB" },
      { name: "Shopian", code: "SHP" },
      { name: "Srinagar", code: "SXR" },
      { name: "Udhampur", code: "UHP" }
    ]
  },
  {
    name: "Ladakh",
    code: "LA",
    cities: [
      { name: "Kargil", code: "KGL" },
      { name: "Leh", code: "IXL" }
    ]
  },
  {
    name: "Lakshadweep",
    code: "LD",
    cities: [
      { name: "Lakshadweep", code: "LKS" }
    ]
  },
  {
    name: "Puducherry",
    code: "PY",
    cities: [
      { name: "Karaikal", code: "KKL" },
      { name: "Mahe", code: "MHE" },
      { name: "Puducherry", code: "PNY" },
      { name: "Yanam", code: "YNM" }
    ]
  }
]

// Metro Cities
export const METRO_CITIES = [
  { name: "Mumbai", code: "BOM", state: "Maharashtra" },
  { name: "Delhi", code: "DEL", state: "Delhi" },
  { name: "Bangalore", code: "BLR", state: "Karnataka" },
  { name: "Hyderabad", code: "HYD", state: "Telangana" },
  { name: "Ahmedabad", code: "AMD", state: "Gujarat" },
  { name: "Chennai", code: "MAA", state: "Tamil Nadu" },
  { name: "Kolkata", code: "CCU", state: "West Bengal" },
  { name: "Surat", code: "SRT", state: "Gujarat" },
  { name: "Pune", code: "PNQ", state: "Maharashtra" },
  { name: "Jaipur", code: "JAI", state: "Rajasthan" },
  { name: "Lucknow", code: "LKO", state: "Uttar Pradesh" },
  { name: "Kanpur", code: "KNU", state: "Uttar Pradesh" },
  { name: "Nagpur", code: "NAG", state: "Maharashtra" },
  { name: "Indore", code: "IDR", state: "Madhya Pradesh" },
  { name: "Thane", code: "TNE", state: "Maharashtra" },
  { name: "Bhopal", code: "BHO", state: "Madhya Pradesh" },
  { name: "Visakhapatnam", code: "VSK", state: "Andhra Pradesh" },
  { name: "Pimpri-Chinchwad", code: "PCC", state: "Maharashtra" },
  { name: "Patna", code: "PAT", state: "Bihar" },
  { name: "Vadodara", code: "VDR", state: "Gujarat" },
  { name: "Ghaziabad", code: "GZB", state: "Uttar Pradesh" },
  { name: "Ludhiana", code: "LUH", state: "Punjab" },
  { name: "Agra", code: "AGR", state: "Uttar Pradesh" },
  { name: "Nashik", code: "NSK", state: "Maharashtra" },
  { name: "Faridabad", code: "FBD", state: "Haryana" },
  { name: "Meerut", code: "MRT", state: "Uttar Pradesh" },
  { name: "Rajkot", code: "RJK", state: "Gujarat" },
  { name: "Kalyan-Dombivali", code: "KLD", state: "Maharashtra" },
  { name: "Vasai-Virar", code: "VVR", state: "Maharashtra" },
  { name: "Varanasi", code: "VNS", state: "Uttar Pradesh" }
]


export function getCityName(code: string): string {
  if (!code) return '';

  // Cache the map for performance
  if (!(global as any)._cityMap) {
    const map = new Map<string, string>();
    INDIAN_STATES.forEach(state => {
      state.cities.forEach(city => {
        map.set(city.code, city.name);
      });
    });
    (global as any)._cityMap = map;
  }

  const map = (global as any)._cityMap as Map<string, string>;
  return map.get(code) || code;
}

